### ISSUE TITLE
Broken contact us form

### ISSUE THREAD

**Issue by Ankesh2004** [anuragverma108/SwapReads#16]
Contact Us form has the following issues which are needed to be fixed  :
1. On clicking send, it reloads the page.
2. Email is not being sent.

Kindly assign me this issue to resolve

**Comment by anuragverma108** [comment]
Any Updates ?

**Comment by jinx-vi-0** [comment]
Hey @anuragverma108 , if @Ankesh2004 is not working on this issue, can you please assign this to me.

**Comment by anuragverma108** [comment]
Assigned! @jinx-vi-0 
Make sure to attach before & after screenshot in your PR.
Make sure to star the repo before working on it! Happy open-source contributing!

**Comment by jinx-vi-0** [comment]
Hey @anuragverma108, just a heads up, it would be great if we could make the confirmation message for sent messages a bit more user-friendly. Instead of an alert, let's consider having a simple message displayed below the contact form. This way, it feels more integrated with the overall user experience.

**Comment by anuragverma108** [comment]
Okay go ahead!

**Comment by jinx-vi-0** [comment]
hey @anuragverma108 , I have created a pr please check it and let me know for any feedback.

**Comment by nilesh5566** [comment]
can you please assign this issue to me #16

**Comment by jinx-vi-0** [comment]
> can you please assign this issue to me #16

I have already solved this issue and submitted a pr.
