### ISSUE TITLE
BUG:Contact us form UI and Address Component

### ISSUE THREAD

**Issue by rupeshv2121** [anuragverma108/SwapReads#2990]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

UI of Contact us form is destroyed also with height and width. Address Block height is too large.

![Contact Form and address](https://github.com/user-attachments/assets/c6363896-f4a8-467c-b313-b09d2dcf244c)

Please assign me under the label of gssoc'24-ext and hacktoberfest

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by rupeshv2121** [comment]
i make a PR for the task

**Comment by Payal-Sinha09** [comment]
Hi, I noticed this issue is focused on UI Improvements in "Get in Touch" and "Address" Section. The current UI for the "Get in Touch" and "Address" sections has several issues:

Broken Image: There is a missing image in the "Get in Touch" form labeled ctc1.
Form Input Styling: The input fields (Name, Email, Subject, Message) lack padding, and the placeholders are not well-aligned, making them less readable.
Address Section Layout: The address section is misaligned and could benefit from a more structured layout, possibly using CSS Grid or Flexbox.
Color and Typography: The font color and styles could be adjusted to improve aesthetics and readability.
Responsive Design: The form and address section need better responsiveness across different screen sizes.

I’d love to help with these improvements as part of GSSoC. Please let me know if I can take this up or assist in implementing the fixes.
![image](https://github.com/user-attachments/assets/5ac5f5df-eaa6-4276-9e46-95246e9dda4b)

**Comment by rupeshv2121** [comment]
I resolve the conflicts Pls check

**Comment by rupeshv2121** [comment]
Pls Merge the Request
