### ISSUE TITLE
BUG: Improve Get in touch div

### ISSUE THREAD

**Issue by Samyak137** [anuragverma108/SwapReads#2995]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

Get in touch div is not looking as much good, the transparent view makes it less attractive and an image is also not visible
![Screenshot 2024-10-05 230019](https://github.com/user-attachments/assets/09fff88a-11cc-4a99-8a1b-38dc6bea20e3)
 
It should be redesign.

### Record

- [X] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Payal-Sinha09** [comment]
Hi, I noticed this issue is focused on improving the "Get in Touch" section. I’d like to add a few more observations:

There’s a broken image labeled ctc1 in the form.
The form input fields lack sufficient padding and alignment.
The "Address" section could benefit from better spacing and alignment using Flexbox or Grid.
I’d love to help with these improvements as part of GSSoC. Please let me know if I can take this up or assist in implementing the fixes.
![image](https://github.com/user-attachments/assets/30bd6216-ffdc-4aa1-8f49-94997e766f31)
