### ISSUE TITLE
BUG: Update Twitter Icon in "Edit Profile" Page.

### ISSUE THREAD

**Issue by Lokesh11868** [anuragverma108/SwapReads#3899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the Edit Profile page, Under Follow Us section, The Twitter logo is not Updated to "X".

![image](https://github.com/user-attachments/assets/129eab66-12dc-4fdd-91b1-f488cea8be9f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by KanishkRaj-RAKA** [comment]
Hii, i'm Kanihk raj, can you assign me this issue

**Comment by abhi03ruchi** [comment]
> Hii, i'm Kanihk raj, can you assign me this issue

this issue is kind of irrelevant . the footer section on the page needs to be updated , it doesnt look good.

chk the my profile page also .
update the footer on these pages --> to the one that is on other pages like [ audio books page] . create a new pr for resolving this issue. 

@KanishkRaj-RAKA  , U can work on this issue .
