### ISSUE TITLE
Replace old twitter icon with new icon

### ISSUE THREAD

**Issue by antriksh-9** [anuragverma108/SwapReads#95]
On the [webiste](https://swapreads.vercel.app/#) under contact section the twitter logo is still the old one.
It needs to be updated.

**Comment by antriksh-9** [comment]
I want to work on this issue. 
Please assign me under GSSoC '24.

**Comment by anuragverma108** [comment]
Assigned!

**Comment by Jatingupta9120** [comment]
Assign this issue to me

**Comment by SalehaTabassum** [comment]
Hi @anuragverma108 assign this issue to me

**Comment by ShrestyTyagi** [comment]
Describe:
The website still contains the old twitter icon. I will replace it with the new twitter icon which will also engage the users by making them feel that the website is up-to-date.

Screenshot:
from ![image](https://github.com/anuragverma108/SwapReads/assets/166687676/b3f03526-f600-4254-aa99-a7c30c11d7e2) -> to  ![image](https://github.com/anuragverma108/SwapReads/assets/166687676/71b009c5-8a29-490e-bc78-050967495629)

I will make sure of the background color so that it matches with the website. 
I will complete it as soon as possible as it gets assigned to me.
I will be highly obliged to you if you could assign it to me. @anuragverma108

**Comment by sahithinandikula** [comment]
@anuragverma108  I can replace the Twitter icon and also add a responsive hover effect on it and make it properly aligned . I hope my request is considered

**Comment by Vedant285** [comment]
@anuragverma108 I can update the logo
